baseURL = "https://www.innenreisebegleitung.de/"
canonifyURLs = true

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

defaultContentLanguage = "de"
languagecode = "de"
disableHugoGeneratorInject = "true"

theme = "hugo-coder"

title = "Moritz Bartl"

[params]
 info = "Innenreisebegleitungen"
 description = "Moritz Bartl. Innenreisebegleitungen."
 favicon_32 = "images/favicon.png"
 favicon_16 = "images/favicon.png"

 avatarURL = "images/moritz-v2.jpg"
 customCSS = ["css/custom.css"]

 author = "Moritz Bartl"

 colorScheme = "auto"
 hideColorSchemeToggle = "true"

 [params.meta]
  keywords = ""

[[menu.main]]
    name ="Kontakt"
    weight = "1"
    url = "contact/"

